version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  django-app:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - mongodb

networks:
  mynetwork:
    driver: bridge